# Generated by Django 5.0.2 on 2024-02-29 10:41

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('suitable_period', models.CharField(choices=[('M', 'morining'), ('E', 'evening'), ('A', 'afternoon')], default='M', max_length=1)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1)])),
                ('avaliable_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('star', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='club.coach')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='class_a', max_length=255)),
                ('description', models.TextField()),
                ('capacity', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('start_time', models.TimeField(null=True)),
                ('date', models.DateField(auto_now=True)),
                ('duration', models.IntegerField()),
                ('level', models.CharField(choices=[('B', 'beginner'), ('I', 'intermediate'), ('A', 'advance')], default='I', max_length=1)),
                ('suitable_period', models.CharField(choices=[('M', 'moring'), ('E', 'evening'), ('A', 'afternoon')], default='M', max_length=1)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.coach')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='club.sport')),
            ],
            options={
                'ordering': ['class_name'],
            },
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('birth_date', models.DateField(null=True)),
                ('ultimate_goal', models.CharField(choices=[('B', 'body building'), ('E', 'earn weight'), ('L', 'lose weight'), ('F', 'fitness')], default='L', max_length=1)),
                ('suitable_period', models.CharField(choices=[('M', 'moring'), ('E', 'evening'), ('A', 'afternoon')], default='M', max_length=1)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainee', to='club.sport')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='ClassItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField()),
                ('status', models.CharField(choices=[('C', 'CONFIRM'), ('A', 'ATTENDED'), ('CA', 'CANCELED'), ('P', 'PENDING')], default='P', max_length=10)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.class')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.trainee')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zip', models.IntegerField()),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='club.trainee')),
            ],
        ),
    ]
